#pragma once
#ifndef __JW_SERIALIZE_INFO_H__
#define __JW_SERIALIZE_INFO_H__
#include "SerializeObject.h"

namespace jw
{
    enum ExpandSerializeObjectType
    {
        EXPAND_SERAILIZE_OBJECT_TYPE_WORLD = SERAILIZE_OBJECT_TYPE_MAX,
        EXPAND_SERAILIZE_OBJECT_TYPE_ROOM,
        EXPAND_SERAILIZE_OBJECT_TYPE_MAX,
    };

    enum SerializeObjectWorldId
    {
        WORLD_SERIALIZE_OBJECT_ID_NONE = 0,
        WORLD_SERIALIZE_OBJECT_ID_START = 1000000,
        WORLD_SERIALIZE_OBJECT_ID_LOGIN = WORLD_SERIALIZE_OBJECT_ID_START,
        WORLD_SERIALIZE_OBJECT_ID_CHAT,
        WORLD_SERIALIZE_OBJECT_ID_CREATE_ROOM,
        WORLD_SERIALIZE_OBJECT_ID_ROOM_LIST,
        WORLD_SERIALIZE_OBJECT_ID_MAX,
    };

    enum SerializeObjectRoomId
    {
        ROOM_SERIALIZE_OBJECT_ID_NONE = 0,
        ROOM_SERIALIZE_OBJECT_ID_START = 2000000,
        ROOM_SERIALIZE_OBJECT_ID_ROOM_CHAT = ROOM_SERIALIZE_OBJECT_ID_START,
        ROOM_SERIALIZE_OBJECT_ID_ROOM_ENTER,
        ROOM_SERIALIZE_OBJECT_ID_MAX,
    };
}
#endif // __JW_SERIALIZE_INFO_H__
